services:
  - type: web
    name: loop-app
    env: node
    buildCommand: npm ci --include=dev && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: loop-db
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: SCOPES
        value: write_products,read_metaobjects,write_metaobjects,read_orders,write_orders,read_customers,write_customers
      - key: SHOPIFY_APP_URL
        sync: false
      - key: APP_URL
        sync: false

databases:
  - name: loop-db
    databaseName: loopdb
    user: loopuser
    plan: starter
