# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b541c11c80c012511c99b477421bcdc6"
name = "shipready-demo"
handle = "shipready-demo"
application_url = "https://original-tower-rome-going.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "codeinspire-app-dev.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_metaobject_definitions,write_metaobjects,write_products,write_themes"

[auth]
redirect_urls = [
  "https://original-tower-rome-going.trycloudflare.com/auth/callback",
  "https://original-tower-rome-going.trycloudflare.com/auth/shopify/callback",
  "https://original-tower-rome-going.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false



